export enum Market {
  STEAMCOMMUNITY = "STEAMCOMMUNITY",
  BUFFMARKET = "BUFFMARKET",
  SKINS = "SKINS",
  SKINPORT = "SKINPORT",
  MARKETCSGO = "MARKETCSGO",
  DMARKET = "DMARKET",
  GAMERPAYGG = "GAMERPAYGG",
  CSDEALS = "CSDEALS",
  SKINBARON = "SKINBARON",
  CSFLOAT = "CSFLOAT",
  CSMONEY = "CSMONEY",
  WHITEMARKET = "WHITEMARKET"
}

export enum Currency {
  EUR = "EUR",
  USD = "USD",
  CNY = "CNY",
  RUB = "RUB",
  INR = "INR"
}


